name: test suite
on:
  push:
    branches-ignore:
        - "gh-readonly-queue/**"
    paths-ignore: ["**/*.md", "**/*.rst", "docs/**", "LICENSE*"]
  pull_request:
    paths-ignore: ["**/*.md", "**/*.rst", "docs/**", "LICENSE*"]
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
env:
  CARGO_BUILD_JOBS: 2

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master; avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.85"
      - name: Cache Cargo sources and tools
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          prefix-key: fastboot-v1-sources
          cache-targets: false
      - run: cargo test --all-targets
      - run: cargo test --doc

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master; avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.85"
          components: rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master; avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.85"
          components: clippy
      - name: Cache Cargo sources and tools
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          prefix-key: fastboot-v1-sources
          cache-targets: false
      - run: cargo clippy -- -D warnings

  allgreen:
    if: always()
    needs:
      - test
      - fmt
      - clippy
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
